# Generated by Django 3.2.10 on 2022-01-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211229_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='mainapp.product')),
            ],
        ),
    ]
