# Generated by Django 3.2.10 on 2022-01-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20220102_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, default='Короткое описание', max_length=255, verbose_name='Короткое описание'),
        ),
    ]
